name: Validate HTML/CSS on PR to Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies locally
        run: |
          npm install --save-dev stylelint stylelint-config-standard htmlhint

      - name: Run HTMLHint
        run: npx htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/*.css"
