name: Deploy-develop

on:
  push:
    branches:
      - develop

permissions: 
  pages: write
  id-token: write

jobs:
  build-develop-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository On the Runner 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Parcel
        run: npm install --save-dev parcel

      - name: Build Website with Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist"
      - name: github-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy-develop-job:
    needs: build-develop-job
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
